version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_dev

  phoenix:
    env_file: .env
    build: .
    ports:
      - 4000:4000
